spring:
  datasource:
    url: jdbc:postgresql://localhost:2022/transactions
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true